CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE TABLE "infrastructure_metric_samples" ("id" TEXT NOT NULL,"sampleKey" TEXT NOT NULL,"component" TEXT NOT NULL,"status" TEXT NOT NULL,"sampledAt" TIMESTAMP(3) NOT NULL,"metrics" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "infrastructure_metric_samples_pkey" PRIMARY KEY ("id"));
CREATE TABLE "api_metric_buckets" ("id" TEXT NOT NULL,"bucketKey" TEXT NOT NULL,"bucketStart" TIMESTAMP(3) NOT NULL,"method" TEXT NOT NULL,"route" TEXT NOT NULL,"applicationId" TEXT,"serviceId" TEXT,"requestCount" INTEGER NOT NULL,"status2xx" INTEGER NOT NULL,"status4xx" INTEGER NOT NULL,"status5xx" INTEGER NOT NULL,"timeoutCount" INTEGER NOT NULL,"errorCount" INTEGER NOT NULL,"concurrentMax" INTEGER NOT NULL,"latencyHistogram" JSONB NOT NULL,"ttfbHistogram" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "api_metric_buckets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "dependency_metric_buckets" ("id" TEXT NOT NULL,"bucketKey" TEXT NOT NULL,"bucketStart" TIMESTAMP(3) NOT NULL,"dependency" TEXT NOT NULL,"operation" TEXT NOT NULL,"callCount" INTEGER NOT NULL,"errorCount" INTEGER NOT NULL,"slowCount" INTEGER NOT NULL,"latencyHistogram" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "dependency_metric_buckets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "metric_rollups" ("id" TEXT NOT NULL,"rollupKey" TEXT NOT NULL,"interval" TEXT NOT NULL,"source" TEXT NOT NULL,"dimension" TEXT NOT NULL,"bucketStart" TIMESTAMP(3) NOT NULL,"metrics" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "metric_rollups_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "infrastructure_metric_samples_sampleKey_key" ON "infrastructure_metric_samples"("sampleKey");
CREATE INDEX "infrastructure_metric_samples_component_sampledAt_idx" ON "infrastructure_metric_samples"("component","sampledAt");
CREATE INDEX "infrastructure_metric_samples_sampledAt_idx" ON "infrastructure_metric_samples"("sampledAt");
CREATE UNIQUE INDEX "api_metric_buckets_bucketKey_key" ON "api_metric_buckets"("bucketKey");
CREATE INDEX "api_metric_buckets_bucketStart_idx" ON "api_metric_buckets"("bucketStart");
CREATE INDEX "api_metric_buckets_route_bucketStart_idx" ON "api_metric_buckets"("route","bucketStart");
CREATE INDEX "api_metric_buckets_applicationId_bucketStart_idx" ON "api_metric_buckets"("applicationId","bucketStart");
CREATE INDEX "api_metric_buckets_serviceId_bucketStart_idx" ON "api_metric_buckets"("serviceId","bucketStart");
CREATE UNIQUE INDEX "dependency_metric_buckets_bucketKey_key" ON "dependency_metric_buckets"("bucketKey");
CREATE INDEX "dependency_metric_buckets_bucketStart_idx" ON "dependency_metric_buckets"("bucketStart");
CREATE INDEX "dependency_metric_buckets_dependency_bucketStart_idx" ON "dependency_metric_buckets"("dependency","bucketStart");
CREATE INDEX "dependency_metric_buckets_operation_bucketStart_idx" ON "dependency_metric_buckets"("operation","bucketStart");
CREATE UNIQUE INDEX "metric_rollups_rollupKey_key" ON "metric_rollups"("rollupKey");
CREATE INDEX "metric_rollups_source_interval_bucketStart_idx" ON "metric_rollups"("source","interval","bucketStart");
CREATE INDEX "metric_rollups_bucketStart_idx" ON "metric_rollups"("bucketStart");
